version: '3.8'

services:
  webapp:
    build: ./webapp
    links:
      - db
    ports:
      - "80:80"
      - "443:443"
    restart: always
    # environment:
    #   - FLASK_APP=/var/www/webapp/run.py
    #   - FLASK_ENV=production
    #   - MYSQL_HOST=db
    #   - MYSQL_PORT=3306
    #   - MYSQL_USER=root
    #   - MYSQL_PASSWORD=root
    #   - MYSQL_DB=myflaskapp
    # volumes:
    #   - ./webapp:/var/www/webapp

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: myflaskapp
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro